### ISSUE TITLE
Support one outfile per server

### ISSUE THREAD

**Issue by foozone** [mimecast/dtail#7]
It would be great if the dtail client could also write one outfile per server. At the moment dtail client only supports writing all output of all servers to one single file `./log/YYYYMMDD.log`. 

This could be enabled by a new command line switch. The outfiles could be named like `./log/YYYYMMDD-SERVERFQDN.log`.

**Comment by pbuetow** [comment]
To do:
1. Refactor logger.go so that the fd, buffers and channels for the log file are encapsulated in a separate struct. This way we can have multiple instances of a log writer. 
2.  An optional parameter to logger.Raw can contain the FQDN of the server which then can be appended to the out file name.

**Comment by pbuetow** [comment]
Not highly desired at the moment.
